### ISSUE TITLE
Debugging Connectors

### ISSUE THREAD

**Issue by mindbreaker** [nielsbosma/SeoTools-for-Excel-Connectors#1]
Is there an option for debugging the connectors?

- Reload the XML File (instead of reopening excel)
- Request / Response for the API calls

Thx

**Comment by nielsbosma** [comment]
Enable debugmode:
http://seotoolsforexcel.com/enable-debug-mode/

This gives you a button in the wizard that reloads connectors without having to restart Excel. 

For HTTP request/response debugging I'm using Fiddler.
