### ISSUE TITLE
Twitch - Blank Cells

### ISSUE THREAD

**Issue by DormaroX** [nielsbosma/SeoTools-for-Excel-Connectors#33]
Hello,

Is the connection for Seo to Twitch still working?
If I run a User Lookup blank or with my usder id, the result is blank for all fields.

Thanks

**Comment by diskborsteMC** [comment]
Yes, it should work. Do you have the latest Seotools version installed?
https://links.seotoolsforexcel.com/latest/

**Comment by DormaroX** [comment]
Yes, downloaded today.
Do I need to add my auth or id to receive the results properly?

**Comment by diskborsteMC** [comment]
You only need to login with your Twitch account when you go into the Twitch connector. Please use the [forums](https://community.seotoolsforexcel.com/) or contact us at info@seotoolsforexcel.com

**Comment by DormaroX** [comment]
Thanks. Will do so!
