### ISSUE TITLE
Binance connector returns empty lines for account specific data

### ISSUE THREAD

**Issue by ggokhanaydin** [nielsbosma/SeoTools-for-Excel-Connectors#37]
Hello,
Binance connector returns empty lines for account specific data. API and secret keys are entered and no error regarding authentication.
<img width="696" alt="image" src="https://user-images.githubusercontent.com/82276257/114275700-c4219480-9a23-11eb-9db2-fb9dc178845c.png">
<img width="792" alt="image" src="https://user-images.githubusercontent.com/82276257/114275707-cd126600-9a23-11eb-967d-76dc432c85f2.png">

**Comment by dovydasm** [comment]
Hi,

Can you check if you're using the most recent version (it should be version 29 if you check via the update manager)? 


What response are you getting from the api? You can check by [enabling the debug mode](https://seotoolsforexcel.com/enable-debug-mode/) and clicking the `Debug: Debugger` link at the very bottom of the connector panel. Please let us know what you see in the *Body* section of the debugger.


![image](https://user-images.githubusercontent.com/836106/114304446-d9f29080-9adb-11eb-843b-f5d2c33bdc12.png)

**Comment by ggokhanaydin** [comment]
Hello,
Please find the debug results below
![image](https://user-images.githubusercontent.com/82276257/115117399-a792d880-9f9e-11eb-961a-17b27090681c.png)
![image](https://user-images.githubusercontent.com/82276257/115117412-b1b4d700-9f9e-11eb-963e-d5e4c715de60.png)
