### ISSUE TITLE
"Local results" are appearing despite the language selected. 

### ISSUE THREAD

**Issue by marilouprot** [nielsbosma/SeoTools-for-Excel-Connectors#38]
![image](https://user-images.githubusercontent.com/82886011/115402262-8d016f00-a1eb-11eb-8635-6049131875b4.png)
When I select a language (I tryed both spanish and italian) for the Google Search > Search Results, the results don't correspond to the language selected but to the country I am now. 
I don't know if the geolocalisation is enable with seotools but here it's a problem because it's not possible to set this parameter and select a geolocalisation so the data are not accurate.

**Comment by diskborsteMC** [comment]
Yes, "Display Language" parameter only controls the displayed language. It is not possible to set the geo location.

**Comment by diskborsteMC** [comment]
I don't see any text in your screenshot, only a list of URLs. Can you write to info@seotoolsforexcel.com and attach example images of results with different langauges? We don't use Github as customer support, except for code related things.
