### ISSUE TITLE
Binance HRESULT error

### ISSUE THREAD

**Issue by dragoncity17** [nielsbosma/SeoTools-for-Excel-Connectors#40]
Hello,
When I want to refresh I delete an empty column (I have only this solution for the moment, tell me if there is better !).

And I have this error :

![gkhohclahhekilbf](https://user-images.githubusercontent.com/19295070/135320177-ba0539bb-5e3c-4bcc-9c03-70e8cb3ae806.png)

Thank you in advance ! :)

**Comment by diskborsteMC** [comment]
Send an email to info@seotoolsforexcel.com. Impossible to say without more context of what is on your sheet. Will close this, not meant for bug reports.
