### ISSUE TITLE
Binance Balance Spot

### ISSUE THREAD

**Issue by dragoncity17** [nielsbosma/SeoTools-for-Excel-Connectors#41]
Hello,
Can you add "Binance Balance Spot" > Connector binance.xml.

For have in dollar our global balance 
![bb](https://user-images.githubusercontent.com/19295070/135728285-fa3c9b92-4e69-41cc-af3a-8ceda79fa555.png)

**Comment by diskborsteMC** [comment]
Balance Spot has been added in view "Account Snapshot". I will close this as it's not meant for feature requests.
