### ISSUE TITLE
Inserting changes cell formatting

### ISSUE THREAD

**Issue by magnusoverli** [nielsbosma/SeoTools-for-Excel-Connectors#42]
Hi!

Just recently found this amazing piece of software, currently testing.
It seems the formatting of the cells are being changed when inserting?
I am trying to insert data from Spotify into a table. I have manually formatted all the cells to have all borders enabled. After inserting data from Spotify, the borders are removed on the cells that data has been inserted into.
Is that something that can be changed/fixed?

**Comment by diskborsteMC** [comment]
Thanks for the suggestion, I'll add it to the todo list for next version.
